// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2kqMKVdIjcX5fqOW-yI1FDBPqRUFZZpo',
    appId: '1:42207404814:web:5665958b6161a0ddbc6d5f',
    messagingSenderId: '42207404814',
    projectId: 'futter-demo-chat',
    authDomain: 'futter-demo-chat.firebaseapp.com',
    storageBucket: 'futter-demo-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMYkMlP5BVj2kkcuv9dD0GHJKjTc-Fczs',
    appId: '1:42207404814:android:e90499f352bdcd37bc6d5f',
    messagingSenderId: '42207404814',
    projectId: 'futter-demo-chat',
    storageBucket: 'futter-demo-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVMqEL6lH9kMPtwD4pffaRP1e6ZXssCBM',
    appId: '1:42207404814:ios:4fa3e9b0bc61c0ddbc6d5f',
    messagingSenderId: '42207404814',
    projectId: 'futter-demo-chat',
    storageBucket: 'futter-demo-chat.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVMqEL6lH9kMPtwD4pffaRP1e6ZXssCBM',
    appId: '1:42207404814:ios:1f89dc04c959b91abc6d5f',
    messagingSenderId: '42207404814',
    projectId: 'futter-demo-chat',
    storageBucket: 'futter-demo-chat.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
